name: sputnik-sr
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - flask
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - seaborn
  - requests
  - beautifulsoup4
  - tqdm
  - pre-commit
  - pytest
